// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecrcaljqjkjqemoeizju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjcmNhbGpxamtqcWVtb2Vpemp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MzYwMDQsImV4cCI6MjA1ODMxMjAwNH0.g9F7U_t4wPFlImYqkRNATtUW6g7iN8E5wV7EOZpQptA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);