// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruyxmxlvvfbxqcrfagur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1eXhteGx2dmZieHFjcmZhZ3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODg3ODcsImV4cCI6MjA1ODU2NDc4N30.mftxZYXkC1fAKPdF46e9PotI7PW2UZ4rGv6Ke3g8dcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);